"""add_telemetry_idempotency_keys

Revision ID: 2e4b30c90918
Revises: 'cd18a09da989'
Create Date: 2026-08-17 11:37:12.687655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4b30c90918'
down_revision: Union[str, None] = 'cd18a09da989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_events', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index('idx_access_idempotency', 'access_events', ['idempotency_key'], unique=True)
    op.add_column('restore_events', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index('idx_restore_idempotency', 'restore_events', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_restore_idempotency', table_name='restore_events')
    op.drop_column('restore_events', 'idempotency_key')
    op.drop_index('idx_access_idempotency', table_name='access_events')
    op.drop_column('access_events', 'idempotency_key')
    # ### end Alembic commands ###
