"""add_sync_logs_table

Revision ID: cd18a09da989
Revises: 'd9efcc49ea94'
Create Date: 2026-08-17 11:22:33.729723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd18a09da989'
down_revision: Union[str, None] = 'd9efcc49ea94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('storage_connection_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('locations_discovered', sa.Integer(), nullable=False),
    sa.Column('objects_discovered', sa.Integer(), nullable=False),
    sa.Column('objects_created', sa.Integer(), nullable=False),
    sa.Column('objects_updated', sa.Integer(), nullable=False),
    sa.Column('objects_failed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_connection_id'], ['storage_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_org_conn', 'connection_sync_logs', ['organization_id', 'storage_connection_id'], unique=False)
    op.create_index('idx_sync_org_status', 'connection_sync_logs', ['organization_id', 'status'], unique=False)
    op.create_index('idx_sync_started', 'connection_sync_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_connection_sync_logs_organization_id'), 'connection_sync_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_connection_sync_logs_storage_connection_id'), 'connection_sync_logs', ['storage_connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_sync_logs_storage_connection_id'), table_name='connection_sync_logs')
    op.drop_index(op.f('ix_connection_sync_logs_organization_id'), table_name='connection_sync_logs')
    op.drop_index('idx_sync_started', table_name='connection_sync_logs')
    op.drop_index('idx_sync_org_status', table_name='connection_sync_logs')
    op.drop_index('idx_sync_org_conn', table_name='connection_sync_logs')
    op.drop_table('connection_sync_logs')
    # ### end Alembic commands ###
