"""initial_database_foundation

Revision ID: d9efcc49ea94
Revises: None
Create Date: 2026-08-17 11:12:57.404015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9efcc49ea94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_org_resource', 'audit_logs', ['organization_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_org_timestamp', 'audit_logs', ['organization_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'OPERATOR', 'VIEWER', name='role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_membership_user')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('storage_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.Enum('AWS_S3', 'AZURE_BLOB', 'GOOGLE_CLOUD_STORAGE', 'LOCAL_S3_COMPATIBLE', name='storage_provider_enum'), nullable=False),
    sa.Column('credential_reference', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_connections_organization_id'), 'storage_connections', ['organization_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_subscription_organization')
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('storage_connection_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_connection_id'], ['storage_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_organization_id'), 'environments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_environments_storage_connection_id'), 'environments', ['storage_connection_id'], unique=False)
    op.create_table('storage_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('storage_connection_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_connection_id'], ['storage_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_connection_id', 'name', name='uq_location_conn_name')
    )
    op.create_index(op.f('ix_storage_locations_organization_id'), 'storage_locations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_storage_locations_storage_connection_id'), 'storage_locations', ['storage_connection_id'], unique=False)
    op.create_table('retention_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('storage_location_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('retention_duration_days', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retention_org_priority', 'retention_policies', ['organization_id', 'priority'], unique=False)
    op.create_index(op.f('ix_retention_policies_environment_id'), 'retention_policies', ['environment_id'], unique=False)
    op.create_index(op.f('ix_retention_policies_organization_id'), 'retention_policies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_retention_policies_storage_location_id'), 'retention_policies', ['storage_location_id'], unique=False)
    op.create_table('storage_cost_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('storage_location_id', sa.UUID(), nullable=False),
    sa.Column('storage_class', sa.String(length=100), nullable=False),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_org_date', 'storage_cost_snapshots', ['organization_id', 'snapshot_date'], unique=False)
    op.create_index('idx_cost_org_loc', 'storage_cost_snapshots', ['organization_id', 'storage_location_id'], unique=False)
    op.create_index(op.f('ix_storage_cost_snapshots_organization_id'), 'storage_cost_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_storage_cost_snapshots_storage_location_id'), 'storage_cost_snapshots', ['storage_location_id'], unique=False)
    op.create_table('storage_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('storage_location_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('object_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('object_type', sa.String(length=255), nullable=True),
    sa.Column('storage_class', sa.String(length=100), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count_30d', sa.Integer(), nullable=False),
    sa.Column('access_count_90d', sa.Integer(), nullable=False),
    sa.Column('version_count', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_location_id', 'object_key', name='uq_object_location_key')
    )
    op.create_index('idx_obj_org_accessed', 'storage_objects', ['organization_id', 'last_accessed_at'], unique=False)
    op.create_index('idx_obj_org_class', 'storage_objects', ['organization_id', 'storage_class'], unique=False)
    op.create_index('idx_obj_org_env', 'storage_objects', ['organization_id', 'environment_id'], unique=False)
    op.create_index('idx_obj_org_loc', 'storage_objects', ['organization_id', 'storage_location_id'], unique=False)
    op.create_index('idx_obj_org_state', 'storage_objects', ['organization_id', 'current_state'], unique=False)
    op.create_index(op.f('ix_storage_objects_environment_id'), 'storage_objects', ['environment_id'], unique=False)
    op.create_index(op.f('ix_storage_objects_organization_id'), 'storage_objects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_storage_objects_storage_location_id'), 'storage_objects', ['storage_location_id'], unique=False)
    op.create_table('access_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['storage_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_access_org_obj', 'access_events', ['organization_id', 'object_id'], unique=False)
    op.create_index('idx_access_timestamp', 'access_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_access_events_object_id'), 'access_events', ['object_id'], unique=False)
    op.create_index(op.f('ix_access_events_organization_id'), 'access_events', ['organization_id'], unique=False)
    op.create_table('legal_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason_reference', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['storage_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_legal_hold_obj_status', 'legal_holds', ['object_id', 'status'], unique=False)
    op.create_index('idx_legal_hold_org_obj', 'legal_holds', ['organization_id', 'object_id'], unique=False)
    op.create_index(op.f('ix_legal_holds_object_id'), 'legal_holds', ['object_id'], unique=False)
    op.create_index(op.f('ix_legal_holds_organization_id'), 'legal_holds', ['organization_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('KEEP', 'MOVE_TO_INFREQUENT_ACCESS', 'ARCHIVE', 'DELETE_CANDIDATE', 'HOLD', name='recommendation_type_enum'), nullable=False),
    sa.Column('current_storage_class', sa.String(length=100), nullable=False),
    sa.Column('recommended_storage_class', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['storage_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_org_obj', 'recommendations', ['organization_id', 'object_id'], unique=False)
    op.create_index('idx_rec_org_status', 'recommendations', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_recommendations_object_id'), 'recommendations', ['object_id'], unique=False)
    op.create_index(op.f('ix_recommendations_organization_id'), 'recommendations', ['organization_id'], unique=False)
    op.create_table('restore_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_storage_class', sa.String(length=100), nullable=False),
    sa.Column('target_storage_class', sa.String(length=100), nullable=False),
    sa.Column('restore_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['storage_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_restore_org_obj', 'restore_events', ['organization_id', 'object_id'], unique=False)
    op.create_index(op.f('ix_restore_events_object_id'), 'restore_events', ['object_id'], unique=False)
    op.create_index(op.f('ix_restore_events_organization_id'), 'restore_events', ['organization_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('requested_action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appr_org_status', 'approval_requests', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_approval_requests_organization_id'), 'approval_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_recommendation_id'), 'approval_requests', ['recommendation_id'], unique=False)
    op.create_table('migration_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('source_storage_class', sa.String(length=100), nullable=False),
    sa.Column('destination_storage_class', sa.String(length=100), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rollback_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['storage_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_migration_org_obj', 'migration_events', ['organization_id', 'object_id'], unique=False)
    op.create_index(op.f('ix_migration_events_object_id'), 'migration_events', ['object_id'], unique=False)
    op.create_index(op.f('ix_migration_events_organization_id'), 'migration_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_migration_events_recommendation_id'), 'migration_events', ['recommendation_id'], unique=False)
    op.create_table('rollback_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('migration_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['migration_id'], ['migration_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rollback_org_mig', 'rollback_events', ['organization_id', 'migration_id'], unique=False)
    op.create_index(op.f('ix_rollback_events_migration_id'), 'rollback_events', ['migration_id'], unique=False)
    op.create_index(op.f('ix_rollback_events_organization_id'), 'rollback_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rollback_events_organization_id'), table_name='rollback_events')
    op.drop_index(op.f('ix_rollback_events_migration_id'), table_name='rollback_events')
    op.drop_index('idx_rollback_org_mig', table_name='rollback_events')
    op.drop_table('rollback_events')
    op.drop_index(op.f('ix_migration_events_recommendation_id'), table_name='migration_events')
    op.drop_index(op.f('ix_migration_events_organization_id'), table_name='migration_events')
    op.drop_index(op.f('ix_migration_events_object_id'), table_name='migration_events')
    op.drop_index('idx_migration_org_obj', table_name='migration_events')
    op.drop_table('migration_events')
    op.drop_index(op.f('ix_approval_requests_recommendation_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_organization_id'), table_name='approval_requests')
    op.drop_index('idx_appr_org_status', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_restore_events_organization_id'), table_name='restore_events')
    op.drop_index(op.f('ix_restore_events_object_id'), table_name='restore_events')
    op.drop_index('idx_restore_org_obj', table_name='restore_events')
    op.drop_table('restore_events')
    op.drop_index(op.f('ix_recommendations_organization_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_object_id'), table_name='recommendations')
    op.drop_index('idx_rec_org_status', table_name='recommendations')
    op.drop_index('idx_rec_org_obj', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_legal_holds_organization_id'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_object_id'), table_name='legal_holds')
    op.drop_index('idx_legal_hold_org_obj', table_name='legal_holds')
    op.drop_index('idx_legal_hold_obj_status', table_name='legal_holds')
    op.drop_table('legal_holds')
    op.drop_index(op.f('ix_access_events_organization_id'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_object_id'), table_name='access_events')
    op.drop_index('idx_access_timestamp', table_name='access_events')
    op.drop_index('idx_access_org_obj', table_name='access_events')
    op.drop_table('access_events')
    op.drop_index(op.f('ix_storage_objects_storage_location_id'), table_name='storage_objects')
    op.drop_index(op.f('ix_storage_objects_organization_id'), table_name='storage_objects')
    op.drop_index(op.f('ix_storage_objects_environment_id'), table_name='storage_objects')
    op.drop_index('idx_obj_org_state', table_name='storage_objects')
    op.drop_index('idx_obj_org_loc', table_name='storage_objects')
    op.drop_index('idx_obj_org_env', table_name='storage_objects')
    op.drop_index('idx_obj_org_class', table_name='storage_objects')
    op.drop_index('idx_obj_org_accessed', table_name='storage_objects')
    op.drop_table('storage_objects')
    op.drop_index(op.f('ix_storage_cost_snapshots_storage_location_id'), table_name='storage_cost_snapshots')
    op.drop_index(op.f('ix_storage_cost_snapshots_organization_id'), table_name='storage_cost_snapshots')
    op.drop_index('idx_cost_org_loc', table_name='storage_cost_snapshots')
    op.drop_index('idx_cost_org_date', table_name='storage_cost_snapshots')
    op.drop_table('storage_cost_snapshots')
    op.drop_index(op.f('ix_retention_policies_storage_location_id'), table_name='retention_policies')
    op.drop_index(op.f('ix_retention_policies_organization_id'), table_name='retention_policies')
    op.drop_index(op.f('ix_retention_policies_environment_id'), table_name='retention_policies')
    op.drop_index('idx_retention_org_priority', table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_storage_locations_storage_connection_id'), table_name='storage_locations')
    op.drop_index(op.f('ix_storage_locations_organization_id'), table_name='storage_locations')
    op.drop_table('storage_locations')
    op.drop_index(op.f('ix_environments_storage_connection_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_organization_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_storage_connections_organization_id'), table_name='storage_connections')
    op.drop_table('storage_connections')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index('idx_audit_org_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_org_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
