"""add_environment_type_columns

Revision ID: db675810abd7
Revises: '9c40c70b4506'
Create Date: 2026-08-17 16:12:54.599206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db675810abd7'
down_revision: Union[str, None] = '9c40c70b4506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('environment_type', sa.String(length=50), nullable=True))
    op.add_column('environments', sa.Column('expected_lifetime_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'expected_lifetime_days')
    op.drop_column('environments', 'environment_type')
    # ### end Alembic commands ###
