"""add_cost_engine_pricing_and_savings_ledger

Revision ID: f1cc8448deac
Revises: 'f8a23838f646'
Create Date: 2026-08-17 15:54:50.614808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cc8448deac'
down_revision: Union[str, None] = 'f8a23838f646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_pricing_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('storage_class', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('price_per_gb_month', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('retrieval_price_per_gb', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('minimum_storage_days', sa.Integer(), nullable=False),
    sa.Column('transition_price_per_gb', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pricing_version', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_active', 'storage_pricing_catalog', ['provider', 'active'], unique=False)
    op.create_index('idx_pricing_lookup', 'storage_pricing_catalog', ['provider', 'storage_class', 'region', 'pricing_version'], unique=True)
    op.create_table('savings_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('migration_id', sa.UUID(), nullable=True),
    sa.Column('source_storage_class', sa.String(length=100), nullable=False),
    sa.Column('destination_storage_class', sa.String(length=100), nullable=False),
    sa.Column('object_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('previous_monthly_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('new_monthly_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('monthly_savings', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('annualized_savings', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_version', sa.String(length=50), nullable=False),
    sa.Column('realized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['migration_id'], ['migration_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['storage_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_savings_migration', 'savings_ledger', ['migration_id'], unique=False)
    op.create_index('idx_savings_org_date', 'savings_ledger', ['organization_id', 'realized_at'], unique=False)
    op.create_index(op.f('ix_savings_ledger_object_id'), 'savings_ledger', ['object_id'], unique=False)
    op.create_index(op.f('ix_savings_ledger_organization_id'), 'savings_ledger', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_ledger_organization_id'), table_name='savings_ledger')
    op.drop_index(op.f('ix_savings_ledger_object_id'), table_name='savings_ledger')
    op.drop_index('idx_savings_org_date', table_name='savings_ledger')
    op.drop_index('idx_savings_migration', table_name='savings_ledger')
    op.drop_table('savings_ledger')
    op.drop_index('idx_pricing_lookup', table_name='storage_pricing_catalog')
    op.drop_index('idx_pricing_active', table_name='storage_pricing_catalog')
    op.drop_table('storage_pricing_catalog')
    # ### end Alembic commands ###
