"""add_object_id_to_retention_policies

Revision ID: f8a23838f646
Revises: '2e4b30c90918'
Create Date: 2026-08-17 11:42:00.219273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a23838f646'
down_revision: Union[str, None] = '2e4b30c90918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retention_policies', sa.Column('object_id', sa.UUID(), nullable=True))
    op.create_index('idx_retention_object', 'retention_policies', ['object_id'], unique=False)
    op.create_index(op.f('ix_retention_policies_object_id'), 'retention_policies', ['object_id'], unique=False)
    op.create_foreign_key(None, 'retention_policies', 'storage_objects', ['object_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'retention_policies', type_='foreignkey')
    op.drop_index(op.f('ix_retention_policies_object_id'), table_name='retention_policies')
    op.drop_index('idx_retention_object', table_name='retention_policies')
    op.drop_column('retention_policies', 'object_id')
    # ### end Alembic commands ###
