import React, { useEffect, useState } from 'react';
import { useOrganization } from '../context/OrganizationContext';
import { getRecommendations, runBatchRecommendations } from '../api/recommendations';
import { submitApprovalDecision } from '../api/approvals';
import { executeRecommendation, rollbackMigration } from '../api/migrations';
import { Recommendation } from '../types';
import { LoadingSpinner, ErrorState, EmptyState } from '../components/Common';
import { RecommendationDetailModal, ApprovalConfirmModal, ExecutionStatusModal } from '../components/Modals';
import { Sparkles, AlertTriangle, Eye } from 'lucide-react';

export const RecommendationsPage: React.FC = () => {
  const { selectedOrg } = useOrganization();
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Filters
  const [typeFilter, setTypeFilter] = useState('ALL');
  const [riskFilter, setRiskFilter] = useState('ALL');
  const [statusFilter, setStatusFilter] = useState('ALL');

  // Modals state
  const [selectedRec, setSelectedRec] = useState<Recommendation | null>(null);
  const [confirmApproveRec, setConfirmApproveRec] = useState<Recommendation | null>(null);
  const [executingRec, setExecutingRec] = useState<Recommendation | null>(null);
  const [executionResult, setExecutionResult] = useState<any | null>(null);
  const [isExecuting, setIsExecuting] = useState(false);

  const loadData = async () => {
    if (!selectedOrg) return;
    setLoading(true);
    setError(null);
    try {
      const res = await getRecommendations(selectedOrg.id, typeFilter, riskFilter, statusFilter);
      setRecommendations(res.items);
    } catch (err: any) {
      setError(err.message || 'Failed to load recommendations.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [selectedOrg?.id, typeFilter, riskFilter, statusFilter]);

  const handleRunBatch = async () => {
    if (!selectedOrg) return;
    setLoading(true);
    try {
      await runBatchRecommendations(selectedOrg.id);
      await loadData();
    } catch (err: any) {
      alert(`Batch recommendation failed: ${err.message}`);
      setLoading(false);
    }
  };

  const handleApproveConfirm = async () => {
    if (!confirmApproveRec || !selectedOrg) return;
    try {
      await submitApprovalDecision(confirmApproveRec.id, 'APPROVE', 'Approved via Control Plane UI', selectedOrg.id);
      setConfirmApproveRec(null);
      await loadData();
    } catch (err: any) {
      alert(`Approval error: ${err.message}`);
    }
  };

  const handleReject = async (rec: Recommendation, reason: string) => {
    if (!selectedOrg) return;
    try {
      await submitApprovalDecision(rec.id, 'REJECT', reason, selectedOrg.id);
      setSelectedRec(null);
      await loadData();
    } catch (err: any) {
      alert(`Rejection error: ${err.message}`);
    }
  };

  const handleExecute = async (rec: Recommendation) => {
    if (!selectedOrg) return;
    setExecutingRec(rec);
    setIsExecuting(true);
    setExecutionResult(null);

    try {
      const res = await executeRecommendation(rec.id, selectedOrg.id);
      setExecutionResult(res);
      await loadData();
    } catch (err: any) {
      setExecutionResult({ status: 'EXECUTION_FAILED', reasons: [err.message] });
    } finally {
      setIsExecuting(false);
    }
  };

  const handleRollback = async (rec: Recommendation) => {
    if (!selectedOrg) return;
    const reason = prompt('Reason for rollback:', 'Operator requested rollback via UI');
    if (!reason) return;
    try {
      const migId = rec.evidence?.migration_id;
      if (!migId) {
        alert('Migration ID not found in recommendation evidence.');
        return;
      }
      await rollbackMigration(migId, reason, selectedOrg.id);
      setSelectedRec(null);
      await loadData();
    } catch (err: any) {
      alert(`Rollback error: ${err.message}`);
    }
  };

  return (
    <div className="page-container space-y-6">
      <div className="page-header flex-between">
        <div>
          <h1 className="page-title">Lifecycle Recommendations</h1>
          <p className="page-subtitle">Explainable storage lifecycle candidates generated by the deterministic decision engine.</p>
        </div>
        <button className="btn btn-primary" onClick={handleRunBatch}>
          <Sparkles className="btn-icon" /> Run Batch Assessment
        </button>
      </div>

      {/* FILTER BAR */}
      <div className="card filter-bar flex-wrap gap-4">
        <div className="filter-group">
          <label className="label">Recommendation:</label>
          <select className="form-select" value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)}>
            <option value="ALL">ALL TYPES</option>
            <option value="KEEP">KEEP</option>
            <option value="MOVE_TO_INFREQUENT_ACCESS">INFREQUENT_ACCESS</option>
            <option value="ARCHIVE">ARCHIVE</option>
            <option value="DELETE_CANDIDATE">DELETE_CANDIDATE</option>
            <option value="HOLD">HOLD</option>
          </select>
        </div>

        <div className="filter-group">
          <label className="label">Risk Level:</label>
          <select className="form-select" value={riskFilter} onChange={(e) => setRiskFilter(e.target.value)}>
            <option value="ALL">ALL RISKS</option>
            <option value="LOW">LOW</option>
            <option value="MEDIUM">MEDIUM</option>
            <option value="HIGH">HIGH</option>
          </select>
        </div>

        <div className="filter-group">
          <label className="label">Status:</label>
          <select className="form-select" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
            <option value="ALL">ALL STATUSES</option>
            <option value="PENDING">PENDING</option>
            <option value="APPROVED">APPROVED</option>
            <option value="REJECTED">REJECTED</option>
            <option value="EXECUTED">EXECUTED</option>
            <option value="BLOCKED">BLOCKED</option>
            <option value="STALE">STALE</option>
          </select>
        </div>
      </div>

      {/* TABLE DATA */}
      {loading ? (
        <LoadingSpinner message="Evaluating storage recommendations..." />
      ) : error ? (
        <ErrorState message={error} onRetry={loadData} />
      ) : recommendations.length === 0 ? (
        <EmptyState title="No Recommendations Found" message="No storage objects matched the selected filters." />
      ) : (
        <div className="card p-0">
          <div className="table-responsive">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Object</th>
                  <th>Age</th>
                  <th>Size</th>
                  <th>Current Class</th>
                  <th>Recommendation</th>
                  <th>Risk</th>
                  <th>Est. Savings</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {recommendations.map((rec) => {
                  const isApproved = rec.status === 'APPROVED';
                  const isExecuted = rec.status === 'EXECUTED';
                  return (
                    <tr key={rec.id}>
                      <td className="font-mono text-xs font-semibold">{rec.object_key}</td>
                      <td>{rec.age_days}d</td>
                      <td>{(rec.object_size_bytes / (1024 * 1024)).toFixed(1)} MB</td>
                      <td><span className="badge badge-neutral">{rec.current_storage_class}</span></td>
                      <td><span className="badge badge-primary">{rec.recommendation_type}</span></td>
                      <td><span className={`badge badge-risk-${rec.risk_level.toLowerCase()}`}>{rec.risk_level}</span></td>
                      <td className="text-success font-semibold">${rec.estimated_savings.toFixed(2)}/mo</td>
                      <td><span className={`badge badge-status-${rec.status.toLowerCase()}`}>{rec.status}</span></td>
                      <td>
                        <div className="flex-align gap-2">
                          <button className="btn btn-secondary btn-sm" onClick={() => setSelectedRec(rec)}>
                            <Eye className="btn-icon" /> View
                          </button>
                          {!isApproved && !isExecuted && rec.status === 'PENDING' && (
                            <button className="btn btn-success btn-sm" onClick={() => setConfirmApproveRec(rec)}>
                              Approve
                            </button>
                          )}
                          {isApproved && (
                            <button className="btn btn-primary btn-sm" onClick={() => handleExecute(rec)}>
                              Execute
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* DETAIL MODAL */}
      <RecommendationDetailModal
        recommendation={selectedRec}
        onClose={() => setSelectedRec(null)}
        onApprove={(rec) => setConfirmApproveRec(rec)}
        onReject={handleReject}
        onExecute={handleExecute}
        onRollback={handleRollback}
      />

      {/* APPROVAL CONFIRM MODAL */}
      <ApprovalConfirmModal
        recommendation={confirmApproveRec}
        onCancel={() => setConfirmApproveRec(null)}
        onConfirm={handleApproveConfirm}
      />

      {/* EXECUTION STATUS MODAL */}
      <ExecutionStatusModal
        recommendation={executingRec}
        executing={isExecuting}
        result={executionResult}
        onClose={() => setExecutingRec(null)}
      />
    </div>
  );
};

export const ApprovalsPage: React.FC = () => {
  const { selectedOrg } = useOrganization();
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [confirmRec, setConfirmRec] = useState<Recommendation | null>(null);

  const loadData = async () => {
    if (!selectedOrg) return;
    setLoading(true);
    setError(null);
    try {
      const res = await getRecommendations(selectedOrg.id, 'ALL', 'ALL', 'PENDING');
      setRecommendations(res.items);
    } catch (err: any) {
      setError(err.message || 'Failed to load approvals queue.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [selectedOrg?.id]);

  const handleApprove = async () => {
    if (!confirmRec || !selectedOrg) return;
    try {
      await submitApprovalDecision(confirmRec.id, 'APPROVE', 'Approved via Approvals Queue UI', selectedOrg.id);
      setConfirmRec(null);
      await loadData();
    } catch (err: any) {
      alert(`Approval error: ${err.message}`);
    }
  };

  const highImpact = recommendations.filter((r) => r.recommendation_type === 'ARCHIVE' || r.recommendation_type === 'DELETE_CANDIDATE');
  const lowImpact = recommendations.filter((r) => r.recommendation_type === 'MOVE_TO_INFREQUENT_ACCESS' || r.recommendation_type === 'KEEP');

  return (
    <div className="page-container space-y-6">
      <div className="page-header">
        <div>
          <h1 className="page-title">Human Approvals Queue</h1>
          <p className="page-subtitle">Review high-impact and low-impact storage recommendations before execution.</p>
        </div>
      </div>

      {loading ? (
        <LoadingSpinner message="Loading pending approval queue..." />
      ) : error ? (
        <ErrorState message={error} onRetry={loadData} />
      ) : recommendations.length === 0 ? (
        <EmptyState title="No Approvals Pending" message="All storage recommendations have been reviewed." />
      ) : (
        <div className="space-y-6">
          {/* HIGH IMPACT QUEUE */}
          <section className="card border-warning">
            <div className="flex-between mb-4">
              <div className="flex-align gap-2">
                <AlertTriangle className="text-warning" />
                <h3 className="card-title">High-Impact Approval Queue ({highImpact.length})</h3>
              </div>
              <span className="badge badge-warning">Requires Explicit Confirmation</span>
            </div>

            {highImpact.length === 0 ? (
              <p className="text-muted text-sm">No high-impact actions pending review.</p>
            ) : (
              <div className="table-responsive">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Object</th>
                      <th>Action</th>
                      <th>Risk</th>
                      <th>Est. Savings</th>
                      <th>Created</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {highImpact.map((r) => (
                      <tr key={r.id}>
                        <td className="font-mono text-xs font-semibold">{r.object_key}</td>
                        <td><span className="badge badge-danger">{r.recommendation_type}</span></td>
                        <td><span className={`badge badge-risk-${r.risk_level.toLowerCase()}`}>{r.risk_level}</span></td>
                        <td className="text-success font-semibold">${r.estimated_savings.toFixed(2)}/mo</td>
                        <td className="text-xs text-muted">{new Date(r.created_at).toLocaleDateString()}</td>
                        <td>
                          <button className="btn btn-success btn-sm" onClick={() => setConfirmRec(r)}>
                            Review & Approve
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </section>

          {/* LOW IMPACT QUEUE */}
          <section className="card">
            <h3 className="card-title mb-4">Standard Approval Queue ({lowImpact.length})</h3>
            {lowImpact.length === 0 ? (
              <p className="text-muted text-sm">No low-impact actions pending review.</p>
            ) : (
              <div className="table-responsive">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Object</th>
                      <th>Action</th>
                      <th>Risk</th>
                      <th>Est. Savings</th>
                      <th>Created</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {lowImpact.map((r) => (
                      <tr key={r.id}>
                        <td className="font-mono text-xs font-semibold">{r.object_key}</td>
                        <td><span className="badge badge-primary">{r.recommendation_type}</span></td>
                        <td><span className={`badge badge-risk-${r.risk_level.toLowerCase()}`}>{r.risk_level}</span></td>
                        <td className="text-success font-semibold">${r.estimated_savings.toFixed(2)}/mo</td>
                        <td className="text-xs text-muted">{new Date(r.created_at).toLocaleDateString()}</td>
                        <td>
                          <button className="btn btn-success btn-sm" onClick={() => setConfirmRec(r)}>
                            Approve
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </section>
        </div>
      )}

      <ApprovalConfirmModal
        recommendation={confirmRec}
        onCancel={() => setConfirmRec(null)}
        onConfirm={handleApprove}
      />
    </div>
  );
};
